name: 'Close Stale Issues and PRs'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'Issue has been automatically marked as stale due to inactivity'
          stale-pr-message: 'PR has been automatically marked as stale due to inactivity'
          days-before-issue-stale: 20
          days-before-pr-stale: 20
          days-before-issue-close: -1
          days-before-pr-close: -1
